# Generated by Django 3.1.7 on 2021-03-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210311_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
